import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./header.js";
import Footer from "./footer.js";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Coca-Cola - FV",
  description: "Generated by create next app",
  icons:{
    icon:[
      '/favicon.ico?v=4'
    ],
    apple:[
      '/apple-touch-icon.png?v=4'
    ],
    shortcut:[
      '/apple-touch-icon.png'
    ]
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        {children} 
        <Footer/>
      </body>
    </html>
  );
}
